name: postgres-db-restore

on:
  workflow_dispatch:

jobs:
  postgres-restore:
    runs-on: ubuntu-latest
    env: 
      AZURE_STORAGE_ACCOUNT: pgdbeus2
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      BACKUP_DATE: ${{ github.run_id }}
      PG_DB_HOST: tr-postgres.postgres.database.azure.com
      PG_DB_USER: kalyan
      PG_DB_PWD: ${{ secrets.PG_DB_PWD }}
      CONTAINER: database-backups/prod
 
    
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
        ref: main 
    
    - name: Install Azure CLI
      run: |
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install -y azure-cli

    # - name: Set Azure environment
    #   id: azure
    #   run: |
    #     if [[ "${{ vars.ENVIRONMENT }}" == "uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat-auto" ]]; then
    #       echo "azure_clientid=${{ secrets.AZURE_CLIENT_ID_UAT }}" >> $GITHUB_ENV
    #       echo "azure_tenantid=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
    #       echo "azure_subscriptionid=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
    #       echo "azure_clientsecret=${{ secrets.AZURE_CLIENT_SECRET_UAT }}" >> $GITHUB_ENV
    #     else
    #       echo "azure_clientid=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
    #       echo "azure_tenantid=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
    #       echo "azure_subscriptionid=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
    #       echo "azure_clientsecret=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
    #     fi

    - name: Login to Azure
      run: az login --use-device-code
    

    # Downloading Dumps from Storage Account
    - name: Downloading DB Dumps from Blob-Storage
      env: 
        CONTAINER: database-backups/prod
        AZURE_STORAGE_ACCOUNT: pgdbeus2
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run:
        # Downloading Non-Prod Data Dumps
        mkdir -p db_dumps/prod
        echo "Downloading Non-Prod dumps..."
        az storage blob download-batch \
          --account-name $AZURE_STORAGE_ACCOUNT \
          --account-key $AZURE_STORAGE_KEY \
          -d db_dumps/prod \
          -s "$CONTAINER" \
          --pattern "*.dump"
     
    - name: List all dumps
      run: ls -lh db_dumps/prod/*.dump

    
    
    # # Restore Prod Dumps to Prod DBs
    # - name: Restoring Prod Dumps to Prod DBs
    #   env:
    #    PG_DB_HOST: tr-postgres.postgres.database.azure.com
    #    PG_DB_USER: kalyan
    #    PG_DB_PWD: ${{ secrets.PG_DB_PWD }}
    #   run: |
        
    #     for dump_file in db_dumps/prod/*.dump; do
    #        db_names=$(ls "$dump_file" | sed -E 's/.*\/(.*)_20[0-9]{2}-[0-9]{2}-[0-9]{2}\.dump$//')
    #        latest_dump=$(ls db_dumps/prod/${db_name}_*.dump | sort | tail -n1)
    #        echo "Processing latest dump for $db_name: $latest_dump"
    #       echo "Checking/creating DB: $db_name"
    #       if PGPASSWORD=${{ secrets.PG_DB_PWD }} \
    #         psql -h $PG_DB_HOST -U $PG_DB_USER -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname = '$db_name';" | grep -q 1; then
    #         echo "Database already exists. Skipping Creation"
    #       else
    #         echo "Database '$db_name' not found. Creating..."
    #         PGPASSWORD=${{ secrets.PG_DB_PWD }} \
    #           psql -h $PG_DB_HOST -U $PG_DB_USER -d postgres -c "CREATE DATABASE \"$db_name\";"
    #           echo "Database Created Successfully"
    #       fi

    #       echo "Restoring data from dump: $dump_file ..."
    #       PGPASSWORD=${{ secrets.PG_DB_PWD }} \
    #         pg_restore -h "$PG_DB_HOST" -U "$PG_DB_USER" -d "$db_name" -c "$latest_dump"
    #         echo "Restore completed for $db_name"
    #     done
